export const majorOptions = [
  { value: 'Accountancy', label: 'Accountancy' },
  { value: 'Accountancy + Data Science', label: 'Accountancy + Data Science' },
  { value: 'ACES Undeclared', label: 'ACES Undeclared' },
  { value: 'Acting', label: 'Acting' },
  { value: 'Actuarial Science', label: 'Actuarial Science' },
  { value: 'Advertising', label: 'Advertising' },
  { value: 'Aerospace Engineering', label: 'Aerospace Engineering' },
  { value: 'African American Studies', label: 'African American Studies' },
  { value: 'Agri-Accounting', label: 'Agri-Accounting' },
  { value: 'Agribusiness, Markets & Management', label: 'Agribusiness, Markets & Management' },
  { value: 'Agricultural and Biological Engineering (ACES)', label: 'Agricultural and Biological Engineering (ACES)' },
  { value: 'Agricultural and Biological Engineering (ENG)', label: 'Agricultural and Biological Engineering (ENG)' },
  { value: 'Agricultural and Consumer Economics', label: 'Agricultural and Consumer Economics' },
  { value: 'Agricultural Communications', label: 'Agricultural Communications' },
  { value: 'Agricultural Education', label: 'Agricultural Education' },
  { value: 'Agricultural Leadership, Education, and Communications', label: 'Agricultural Leadership, Education, and Communications' },
  { value: 'Agronomy', label: 'Agronomy' },
  { value: 'Animal Sciences', label: 'Animal Sciences' },
  { value: 'Anthropology', label: 'Anthropology' },
  { value: 'Architectural Studies', label: 'Architectural Studies' },
  { value: 'Art and Art History', label: 'Art and Art History' },
  { value: 'Art Education (K-12)', label: 'Art Education (K-12)' },
  { value: 'Art Undeclared', label: 'Art Undeclared' },
  { value: 'Arts and Entertainment Technology', label: 'Arts and Entertainment Technology' },
  { value: 'Asian American Studies', label: 'Asian American Studies' },
  { value: 'Astronomy', label: 'Astronomy' },
  { value: 'Astronomy + Data Science', label: 'Astronomy + Data Science' },
  { value: 'Astrophysics', label: 'Astrophysics' },
  { value: 'Atmospheric Sciences', label: 'Atmospheric Sciences' },
  { value: 'Biochemistry', label: 'Biochemistry' },
  { value: 'Bioengineering', label: 'Bioengineering' },
  { value: 'Biology', label: 'Biology' },
  { value: 'Brain and Cognitive Science', label: 'Brain and Cognitive Science' },
  { value: 'Business + Data Science', label: 'Business + Data Science' },
  { value: 'Business Undeclared', label: 'Business Undeclared' },
  { value: 'Chemical Engineering', label: 'Chemical Engineering' },
  { value: 'Chemistry', label: 'Chemistry' },
  { value: 'Civil Engineering', label: 'Civil Engineering' },
  { value: 'Classics', label: 'Classics' },
  { value: 'Communication', label: 'Communication' },
  { value: 'Community Health', label: 'Community Health' },
  { value: 'Comparative and World Literature', label: 'Comparative and World Literature' },
  { value: 'Computer Engineering', label: 'Computer Engineering' },
  { value: 'Computer Science', label: 'Computer Science' },
  { value: 'Computer Science and Advertising', label: 'Computer Science and Advertising' },
  { value: 'Computer Science and Animal Sciences', label: 'Computer Science and Animal Sciences' },
  { value: 'Computer Science and Anthropology', label: 'Computer Science and Anthropology' },
  { value: 'Computer Science and Astronomy', label: 'Computer Science and Astronomy' },
  { value: 'Computer Science and Bioengineering', label: 'Computer Science and Bioengineering' },
  { value: 'Computer Science and Chemistry', label: 'Computer Science and Chemistry' },
  { value: 'Computer Science and Crop Sciences', label: 'Computer Science and Crop Sciences' },
  { value: 'Computer Science and Economics', label: 'Computer Science and Economics' },
  { value: 'Computer Science and Education, Learning Sciences', label: 'Computer Science and Education, Learning Sciences' },
  { value: 'Computer Science and Education, Secondary Education', label: 'Computer Science and Education, Secondary Education' },
  { value: 'Computer Science and Geography & Geographic Information Science', label: 'Computer Science and Geography & Geographic Information Science' },
  { value: 'Computer Science and Linguistics', label: 'Computer Science and Linguistics' },
  { value: 'Computer Science and Music', label: 'Computer Science and Music' },
  { value: 'Computer Science and Philosophy', label: 'Computer Science and Philosophy' },
  { value: 'Computer Science and Physics', label: 'Computer Science and Physics' },
  { value: 'Consumer Economics & Finance', label: 'Consumer Economics & Finance' },
  { value: 'Costume Design and Technology', label: 'Costume Design and Technology' },
  { value: 'Creative Writing', label: 'Creative Writing' },
  { value: 'Crop Sciences', label: 'Crop Sciences' },
  { value: 'Dance (BA)', label: 'Dance (BA)' },
  { value: 'Dance (BFA)', label: 'Dance (BFA)' },
  { value: 'Dance, BA and Kinesiology, BS (Dual Degree Program)', label: 'Dance, BA and Kinesiology, BS (Dual Degree Program)' },
  { value: 'Dietetics and Nutrition', label: 'Dietetics and Nutrition' },
  { value: 'Early Childhood Education (Birth-Grade 2)', label: 'Early Childhood Education (Birth-Grade 2)' },
  { value: 'Earth, Society, and Environmental Sustainability', label: 'Earth, Society, and Environmental Sustainability' },
  { value: 'East Asian Languages and Cultures', label: 'East Asian Languages and Cultures' },
  { value: 'Econometrics and Quantitative Economics', label: 'Econometrics and Quantitative Economics' },
  { value: 'Economics', label: 'Economics' },
  { value: 'Electrical Engineering', label: 'Electrical Engineering' },
  { value: 'Elementary Education (Grades 1-6)', label: 'Elementary Education (Grades 1-6)' },
  { value: 'Engineering Mechanics', label: 'Engineering Mechanics' },
  { value: 'Engineering Technology and Management for Agricultural Systems', label: 'Engineering Technology and Management for Agricultural Systems' },
  { value: 'Engineering Undeclared', label: 'Engineering Undeclared' },
  { value: 'English', label: 'English' },
  { value: 'Environmental Economics & Policy', label: 'Environmental Economics & Policy' },
  { value: 'Environmental Engineering', label: 'Environmental Engineering' },
  { value: 'Farm Management', label: 'Farm Management' },
  { value: 'Finance', label: 'Finance' },
  { value: 'Finance + Data Science', label: 'Finance + Data Science' },
  { value: 'Finance in Agri-Business', label: 'Finance in Agri-Business' },
  { value: 'Financial Planning', label: 'Financial Planning' },
  { value: 'Food Science', label: 'Food Science' },
  { value: 'French', label: 'French' },
  { value: 'Gender and Women\'s Studies', label: 'Gender and Women\'s Studies' },
  { value: 'Geography and Geographic Information Science', label: 'Geography and Geographic Information Science' },
  { value: 'Geology', label: 'Geology' },
  { value: 'Germanic Studies', label: 'Germanic Studies' },
  { value: 'Global Studies', label: 'Global Studies' },
  { value: 'Graphic Design', label: 'Graphic Design' },
  { value: 'Health Sciences, Interdisciplinary', label: 'Health Sciences, Interdisciplinary' },
  { value: 'History', label: 'History' },
  { value: 'History of Art', label: 'History of Art' },
  { value: 'Hospitality Management', label: 'Hospitality Management' },
  { value: 'Human Development and Family Studies', label: 'Human Development and Family Studies' },
  { value: 'Industrial Engineering', label: 'Industrial Engineering' },
  { value: 'Information Sciences', label: 'Information Sciences' },
  { value: 'Information Sciences + Data Science', label: 'Information Sciences + Data Science' },
  { value: 'Information Systems', label: 'Information Systems' },
  { value: 'Integrative Biology', label: 'Integrative Biology' },
  { value: 'Interdisciplinary Studies', label: 'Interdisciplinary Studies' },
  { value: 'Italian', label: 'Italian' },
  { value: 'Jazz Performance', label: 'Jazz Performance' },
  { value: 'Journalism', label: 'Journalism' },
  { value: 'Kinesiology', label: 'Kinesiology' },
  { value: 'Landscape Architecture', label: 'Landscape Architecture' },
  { value: 'LAS Undeclared', label: 'LAS Undeclared' },
  { value: 'Latin American Studies', label: 'Latin American Studies' },
  { value: 'Latina/Latino Studies', label: 'Latina/Latino Studies' },
  { value: 'Learning and Education Studies', label: 'Learning and Education Studies' },
  { value: 'Lighting Design and Technology', label: 'Lighting Design and Technology' },
  { value: 'Linguistics', label: 'Linguistics' },
  { value: 'Linguistics and Teaching English as a Second Language', label: 'Linguistics and Teaching English as a Second Language' },
  { value: 'Lyric Theatre', label: 'Lyric Theatre' },
  { value: 'Management', label: 'Management' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Materials Science and Engineering', label: 'Materials Science and Engineering' },
  { value: 'Mathematics', label: 'Mathematics' },
  { value: 'Mathematics and Computer Science', label: 'Mathematics and Computer Science' },
  { value: 'Mechanical Engineering', label: 'Mechanical Engineering' },
  { value: 'Media and Cinema Studies', label: 'Media and Cinema Studies' },
  { value: 'Middle Grades Education (Grades 5-8)', label: 'Middle Grades Education (Grades 5-8)' },
  { value: 'Molecular and Cellular Biology', label: 'Molecular and Cellular Biology' },
  { value: 'Music', label: 'Music' },
  { value: 'Music Composition', label: 'Music Composition' },
  { value: 'Music Education (K-12)', label: 'Music Education (K-12)' },
  { value: 'Music Instrumental Performance', label: 'Music Instrumental Performance' },
  { value: 'Music Open Studies', label: 'Music Open Studies' },
  { value: 'Music Voice Performance', label: 'Music Voice Performance' },
  { value: 'Musicology', label: 'Musicology' },
  { value: 'Natural Resources and Environmental Sciences', label: 'Natural Resources and Environmental Sciences' },
  { value: 'Neural Engineering', label: 'Neural Engineering' },
  { value: 'Neuroscience', label: 'Neuroscience' },
  { value: 'Nuclear, Plasma, and Radiological Engineering', label: 'Nuclear, Plasma, and Radiological Engineering' },
  { value: 'Nutrition and Health', label: 'Nutrition and Health' },
  { value: 'Operations Management', label: 'Operations Management' },
  { value: 'Organizational and Community Leadership', label: 'Organizational and Community Leadership' },
  { value: 'Philosophy', label: 'Philosophy' },
  { value: 'Physics', label: 'Physics' },
  { value: 'Plant Biotechnology', label: 'Plant Biotechnology' },
  { value: 'Policy, International Trade & Development', label: 'Policy, International Trade & Development' },
  { value: 'Political Science', label: 'Political Science' },
  { value: 'Portuguese', label: 'Portuguese' },
  { value: 'Psychology', label: 'Psychology' },
  { value: 'Public Policy & Law', label: 'Public Policy & Law' },
  { value: 'Recreation, Sport and Tourism', label: 'Recreation, Sport and Tourism' },
  { value: 'Religion', label: 'Religion' },
  { value: 'Russian, East European, and Eurasian Studies', label: 'Russian, East European, and Eurasian Studies' },
  { value: 'Scenic Design', label: 'Scenic Design' },
  { value: 'Scenic Technology', label: 'Scenic Technology' },
  { value: 'Secondary Education', label: 'Secondary Education' },
  { value: 'Secondary Education: Biology', label: 'Secondary Education: Biology' },
  { value: 'Secondary Education: Chemistry', label: 'Secondary Education: Chemistry' },
  { value: 'Secondary Education: Earth Science', label: 'Secondary Education: Earth Science' },
  { value: 'Secondary Education: English', label: 'Secondary Education: English' },
  { value: 'Secondary Education: Mathematics', label: 'Secondary Education: Mathematics' },
  { value: 'Secondary Education: Mathematics (LAS)', label: 'Secondary Education: Mathematics (LAS)' },
  { value: 'Secondary Education: Physics', label: 'Secondary Education: Physics' },
  { value: 'Secondary Education: Social Studies', label: 'Secondary Education: Social Studies' },
  { value: 'Slavic Studies', label: 'Slavic Studies' },
  { value: 'Social Work', label: 'Social Work' },
  { value: 'Sociology', label: 'Sociology' },
  { value: 'Sound Design and Technology', label: 'Sound Design and Technology' },
  { value: 'Spanish', label: 'Spanish' },
  { value: 'Special Education', label: 'Special Education' },
  { value: 'Speech and Hearing Science', label: 'Speech and Hearing Science' },
  { value: 'Stage Management', label: 'Stage Management' },
  { value: 'Statistics', label: 'Statistics' },
  { value: 'Statistics and Computer Science', label: 'Statistics and Computer Science' },
  { value: 'Strategy, Innovation and Entrepreneurship', label: 'Strategy, Innovation and Entrepreneurship' },
  { value: 'Studio Art (BA)', label: 'Studio Art (BA)' },
  { value: 'Studio Art (BFA)', label: 'Studio Art (BFA)' },
  { value: 'Supply Chain Management', label: 'Supply Chain Management' },
  { value: 'Sustainability in Food & Environmental Systems', label: 'Sustainability in Food & Environmental Systems' },
  { value: 'Sustainable Design', label: 'Sustainable Design' },
  { value: 'Systems Engineering and Design', label: 'Systems Engineering and Design' },
  { value: 'Teacher Education: French (K-12)', label: 'Teacher Education: French (K-12)' },
  { value: 'Teacher Education: German (K-12)', label: 'Teacher Education: German (K-12)' },
  { value: 'Teacher Education: Kinesiology - Physical Education (K-12)', label: 'Teacher Education: Kinesiology - Physical Education (K-12)' },
  { value: 'Teacher Education: Spanish (K-12)', label: 'Teacher Education: Spanish (K-12)' },
  { value: 'Theatre Studies', label: 'Theatre Studies' },
  { value: 'Undeclared', label: 'Undeclared' },
  { value: 'Urban Studies and Planning', label: 'Urban Studies and Planning' }
];
